### ISSUE TITLE
[Win10-Inoreader] After attempting to connect to Inoreader, Raven Reader mostly freezes

### ISSUE THREAD

**Issue by Feldherren** [hello-efficiency-inc/raven-reader#561]
**Describe the bug**
Downloaded and installed fresh copy of Raven Reader. Went into preferences > sync account, connected it to Inoreader. Raven Reader remained responsive for a few seconds (not showing posts from Inoreader), then mostly froze; the menu bar remains interactable and clicking will still show submenus, but attempting to access or do anything from it will not work.
Raven Reader also remembers that the Inoreader connection has been made (if you're quick, you can get to Preferences: Sync Account and see that it's still in there), and will now freeze a few seconds after opening. 

**To Reproduce**
1. Downloaded Raven Reader
2. Menu: Raven Reader > Preferences > Sync Account > connect to Inoreader
3. Go through setting up Inoreader connection
4. Wait a few seconds
5. Raven Reader mostly-freezes

**Expected behavior**
That Raven Reader would remain responsive, and/or have some sort of indication that it's completely busy working on syncing with Inoreader.

**Screenshots**
N/A - screenshots don't really show the application is frozen.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 20H2

**Additional context**
If you're really quick, on opening Raven Reader you can get Preferences open and get to the Sync Accounts screen before nearly-everything freezes. I haven't tried disconnecting the Inoreader connection, as I don't know whether Raven Reader is legitimately having problems, or whether it's just taking a long time to sync with Inoreader and not indicating it.

**Comment by mrgodhani** [comment]
Upon investigating on windows 10 I was not able to reproduce the issue.

**Comment by HueLiu** [comment]
Hi, 

I'm in exactly the same situation. I can access inoreader.com normally and also click the Authorization button. But has been stuck in this picture, waiting for ten minutes is still the same.

CPU takes up a lot of time, but it doesn't seem to be working properly.

I also tried to mark all inoreader articles as read, hoping to avoid triggering the API limit, but unfortunately the situation remains the same.


OS: Windows 10 Pro too
Version 21H1



![图片](https://user-images.githubusercontent.com/19755727/124066618-9882d900-da6b-11eb-8742-2bd8d20b7d0b.png)


![图片](https://user-images.githubusercontent.com/19755727/124066461-49d53f00-da6b-11eb-973b-559a7e5f3403.png)

**Comment by hiomair** [comment]
Am also experiencing this issue as described. Installed app, was able to interact and set preferences. Logged into Inoreader, app has mostly remained frozen since. First assumption was long initial sync time, so I left it running for long while. Eventually thought maybe it needed to be restarted, and have not been able to access anything beyond viewing the menu buttons. No response when clicking anything. As mentioned in initial report, am able to interact as expected for the first few seconds after launch. CPU usage is also high as mentioned in the previous to this: Ryzen 7 5800x spiking up to mid 80% usage, closing out all Raven processes drops it back to expected 5-10%. Have also manually allowed Raven through firewall based on another thread regarding Inoreader snyc. Renderer log only states "Processing Inoreader feeds" on multiple lines. Installed version is 1.0.63, installed via Chocolatey. Please let me know if any other information can be offered to help.
